version: "0.2"
words:
  - adafruit
  - autoattribute
  - autoclass
  - automethod
  - ANYMEAS
  - ASIC
  - baudrate
  - busio
  - circuitpython
  - datasheet
  - digitalio
  - intellimouse
  - micropython
  - MOSI
  - Muxing
  - pipx
  - seealso
  - sparkfun
  - tolower
  - trackpad
  - trackpads
